-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id integer NOT NULL,
    category text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_id integer NOT NULL,
    product integer NOT NULL,
    qty integer,
    CONSTRAINT order_id_pkey PRIMARY KEY (order_id, product)
);

CREATE TABLE IF NOT EXISTS public.proizvoditel
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT proizvoditel_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.punkt_vidachi
(
    id integer NOT NULL,
    adress bigint,
    CONSTRAINT punkt_vidachi_import_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    id integer NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.statuses
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT statuses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL,
    midle_name text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    login text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT user_import_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.zakaz
(
    number_za integer NOT NULL,
    date_zakaza date NOT NULL,
    date_dostavki date NOT NULL,
    adress_punkta_vidachi integer NOT NULL,
    code integer NOT NULL,
    user_id integer NOT NULL,
    status_id integer NOT NULL,
    CONSTRAINT zakaz_import_pkey PRIMARY KEY (number_za)
);

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zakaz
    ADD CONSTRAINT zakaz_adress_punkta_vidachi_fkey FOREIGN KEY (adress_punkta_vidachi)
    REFERENCES public.punkt_vidachi (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zakaz
    ADD CONSTRAINT zakaz_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.statuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.zakaz
    ADD CONSTRAINT zakaz_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;